---
title: "Número de óbitos de Salvador por faixa etária:"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    runtime: shiny
    output: html_document
---



```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(ggplot2)
library("readr")
library("dplyr")
library("tidyr")
library(ggthemes)
library(extrafont)
library(gganimate)
library(ggplotlyExtra)
library(plotly)
library(ggplotify)


library(echarts4r) # charts
library(tidyverse) # general use
library(lubridate) # dates and times
library(prophet) # forecasting
library(scales)

# Biblioteca para carregamento automatico de dados 
library(readr)
saude_v00 <- read_delim("data/A104333177_180_116_165.csv",";", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"),trim_ws = TRUE)
  
nomes <- names(saude_v00)
nomes <- nomes[2:length(nomes)]
# Contrucao de graficos

library(dplyr)
library(ggplot2)
library(gridExtra)
library(rlang)   # !!sym()

```

Inputs {.sidebar}
-------------------------------------------------------------

```{r, echo=FALSE}
selectInput("faixa", label = "Faixa etária:",
            choices = nomes, selected = nomes[1])
```

Column
--------------------------------------------------------------

```{r,eval=TRUE, echo=FALSE}
renderPlotly({
	ggplotly(objeto <- saude_v00 %>% 
  ggplot(aes(x=`ano do óbito`,y=!!sym(input$faixa))) +
  geom_line(fill="#6cbfd3",color="#fac113",size=2) +
  labs(
    title = "",
    x = "Ano",
    y = "Nº"
  ) +
  theme(title = element_text(size = 12,colour = "#db4470"))+
  theme(axis.title.x=element_text(size=11)) +
  theme(axis.title.y=element_text(size=11)) +
  theme(legend.text=element_text(size =11)) +
  theme(axis.text=element_text(size =11))  +
  theme(legend.position = "none")+
  theme(panel.grid = element_blank(), axis.ticks.y = element_line())+
  theme(panel.border = element_rect(fill=NA, color = "#64D2AA", size = 2))+
  theme(panel.background = element_rect(fill=NA,color = "gray70", size = 2),
        panel.grid.major = element_line(color = "gray70", size = .95),
        panel.grid.minor = element_line(color = "gray70", size = .25)))
})
```
